title: AI and Creativity Workshop
#logo: /assets/img/logo.png
description: A website for PRG's AI and Creativity Workshop. For any questions and suggestions, please contact : 

* Safinah Ali : safinah@mit.edu
* Nisha Devasia : ndevasia@mit.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
